name: Deploy Next.js statically built site to GitHub Pages
on:
  push:
    branches: "main"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup Pages with Next.js configuration
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next

      - name: Install dependencies
        run: npm install
        working-directory: next.js-crash-course

      - name: Build with Next.js
        run: npm run build
        working-directory: next.js-crash-course

      - name: Upload statically built files for deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: next.js-crash-course/out

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
